Resources:
  NotifierTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${file(env.yml):TopicName}

  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: ${file(env.yml):SubscriberEmail}
      Protocol: email
      TopicArn: !Ref "NotifierTopic"

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: DictionaryAPIKey
      Description: Aithenticator Api Key for API Gateway
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      Description: Aithenticator Api Usage plan
      UsagePlanName: Aithenticator Api Usage plan
