service: authservice
frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-plugin-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    RoleName:  ${file(env.yml):RoleName}
    TopicName: ${file(env.yml):TopicName}
    TopicARN:  arn:aws:sns:${aws:region}:${aws:accountId}:${self:provider.environment.TopicName}
  stage: prod
  region:   ${file(env.yml):REGION}

custom:
  prune:
    automatic: true
    number: 5

  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: npm

functions:
  - ${file(functions.yml)}

resources:
 - ${file(cloud-formation.yml)}
