#
service: authservice
frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-plugin-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    RoleName: prod/role_name
  # you can overwrite defaults here
  stage: prod
  region: ap-south-1

custom:
  prune:
    automatic: true
    number: 3

  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: npm

functions:
  - ${file(functions.yml)}
