name: Build and Delpoy app
run-name: ${{ github.actor }}
on:
  push:
    branches: [master]

jobs:
  workflow:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: echo "Build started"
      - run: npm i
      - run: npm i serverless@3 -g
      - run: echo "Dependency install completed"
      - run: echo "Configuring aws CLI"      
      - run: aws --version
      - run: getCred.sh ${{ secrets.API_DOMAIN }} ${{ secrets.API_KEY }} 
        shell: bash
      - name: Deploying into AWS
        run: |
            echo "Deploying using serverless."
            sls deploy --force
            echo "Deployment completed successsfully"
            echo "Removing credentials"
            removeCred.sh
          
